### ISSUE TITLE
Implement endangered movement

### ISSUE THREAD

**Issue by Labrasones** [NikVidya/Lair-Thief#5]
The player currently can only move with regular movement. Please implement a check to see if the player is endangered, and then utilize one of the other movement zone variables that are provided.

**Comment by nmasdev** [comment]
I've added endangered movement to my branch by making a check on the player agent to see if position y is less than 2, and then had the onturnstart and update functions use this check with a bool[,] variable. I don't want to mess anything up though so i made it a fork instead of committing to master

**Comment by Labrasones** [comment]
I've added a 'dev' branch. Feel free to merge stuff into that, even if it might break something. We'll merge dev into master when dev is stable.

If we wanted to go all out, we could create a qa branch or something. So the flow would be 
feature branch ->dev -> qa -> master


Also, don't forget that the danger zone grows as the game progresses. Make sure the check is using a variable, not a hard coded, magic number.
